[package]
name = "consul-rs"
version = "0.1.0"
authors = ["vizee <vizee@live.cn>"]

[dependencies]
http = "0.1"
hyper = "0.12"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
percent-encoding = "1.0"
